# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "podcast-it eval"

prompts:
  - file://messages.template.json
  

providers:
  - id: "openai:gpt-4o-2024-08-06"
    config:
      response_schema: ./schemas/podcast-script.schema.json

defaultTest:
  vars:
    system: file://../src/endpoints/episodeCreatePrompt.txt
    hosts: "[ { \"name\": \"Alice\", \"voice\": \"ash\" }, { \"name\": \"Bob\", \"voice\": \"alloy\" } ]"

tests:
  - vars:
      content: bananas

  - vars:
      content: avocado toast
    assert:
      # For more information on assertions, see https://promptfoo.dev/docs/configuration/expected-outputs

      # Make sure output contains the word "avocado"
      - type: icontains
        value: avocado

      # Prefer shorter outputs
      - type: javascript
        value: 1 / (output.length + 1)

  - vars:
      content: new york city
    assert:
      # For more information on model-graded evals, see https://promptfoo.dev/docs/configuration/expected-outputs/model-graded
      - type: llm-rubric
        value: ensure that the output is conversational

